### PR TITLE
Add possibility to create networks

### PR DESCRIPTION
**Pull request by ggggut**
Added possibility to create networks for test runs.
Please let me know if something is not good on your side.

Thank You and Greetings from Hetzner Cloud!

### CODE REVIEW

**Comment by decentral1se** [comment]
Heyyy @ggggut thanks for this :rocket: I'm gonna take it for a test run now and if all goes well, make the release.

> ... Greetings from Hetzner Cloud!

I'd like to take this opportunity to again emphasise that if Hetnzer GmbH are using this software internally then they should support the maintenance of it. Financial sponsorship is easier than ever, please see https://github.com/ansible-community/molecule-hetznercloud#support for how to do that. I've worked at tech companies where I also petitioned management to support open source so there is also something you can do as a worker. Thanks for considering :sun_with_face:

**Comment by decentral1se** [comment]
OK, it seems the network logic requires the installation of the `python-netaddr`package to do its work so we need to add a conditional check to install that package if the networks configuration in included. Will get around to this shortly.

**Comment by decentral1se** [comment]
> OK, it seems the network logic requires the installation of the `python-netaddr`package to do its work so we need to add a conditional check to install that package if the networks configuration in included. This happens in the create phase so I will have to add this directly to the create.yml. Will get around to this shortly.

Or not.

image


@ggggut I am seeing the following error:

> TASK [Create private subnetwork(s)] ********************************************
> changed: [localhost] => (item={'ip': '10.10.10.1/24', 'network_zone': 'eu-central', 'type': 'cloud', 'server_name': 'molecule-hetznercloud-31006', 'network_name': 'molecule-hetznercloud-network-1'})
> changed: [localhost] => (item={'ip': '10.20.10.1/24', 'server_name': 'molecule-hetznercloud-31006', 'network_name': 'molecule-hetznercloud-network-2'})
> 
> TASK [Attach Server to Subnetwork(s)] ******************************************
> An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: 'NoneType' object has no attribute 'private_net'
> failed: [localhost] (item={'ip': '10.10.10.1/24', 'network_zone': 'eu-central', 'type': 'cloud', 'server_name': 'molecule-hetznercloud-31006', 'network_name': 'molecule-hetznercloud-network-1'}) => {"ansible_loop_var": "item", "changed": false, "item": {"ip": "10.10.10.1/24", "network_name": "molecule-hetznercloud-network-1", "network_zone": "eu-central", "server_name": "molecule-hetznercloud-31006", "type": "cloud"}, "module_stderr": "Traceback (most recent call last):\n  File \"/home/decentral1se/.ansible/tmp/ansible-tmp-1622588484.490953-18026-166838752582389/AnsiballZ_hcloud_server_network.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/home/decentral1se/.ansible/tmp/ansible-tmp-1622588484.490953-18026-166838752582389/AnsiballZ_hcloud_server_network.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/decentral1se/.ansible/tmp/ansible-tmp-1622588484.490953-18026-166838752582389/AnsiballZ_hcloud_server_network.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.hetzner.hcloud.plugins.modules.hcloud_server_network', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/home/decentral1se/.pyenv/versions/3.9.0/lib/python3.9/runpy.py\", line 210, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/home/decentral1se/.pyenv/versions/3.9.0/lib/python3.9/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/home/decentral1se/.pyenv/versions/3.9.0/lib/python3.9/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_hcloud_server_network_payload_v7up5vhe/ansible_hcloud_server_network_payload.zip/ansible_collections/hetzner/hcloud/plugins/modules/hcloud_server_network.py\", line 243, in <module>\n  File \"/tmp/ansible_hcloud_server_network_payload_v7up5vhe/ansible_hcloud_server_network_payload.zip/ansible_collections/hetzner/hcloud/plugins/modules/hcloud_server_network.py\", line 237, in main\n  File \"/tmp/ansible_hcloud_server_network_payload_v7up5vhe/ansible_hcloud_server_network_payload.zip/ansible_collections/hetzner/hcloud/plugins/modules/hcloud_server_network.py\", line 196, in present_server_network\n  File \"/tmp/ansible_hcloud_server_network_payload_v7up5vhe/ansible_hcloud_server_network_payload.zip/ansible_collections/hetzner/hcloud/plugins/modules/hcloud_server_network.py\", line 152, in _get_server_network\nAttributeError: 'NoneType' object has no attribute 'private_net'\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
> 

Perhaps thing would go smoother if you run the integration tests yourself? You can do this by following the steps listed in https://github.com/ansible-collections/hetzner.hcloud/issues/47#issuecomment-851455710. If you could add the `netaddr` pacakge to the CI setup, that'd be great https://github.com/ansible-community/molecule-hetznercloud/blob/main/.drone.yml#L84

**Comment by ggggut** [comment]
Hi @decentral1se, we did several integration tests before and everything worked.
Also right now I followed all steps you provided and on my side again everything works.

```
TASK [Create private subnetwork(s)] ********************************************
changed: [localhost] => (item={'ip': '10.10.10.1/24', 'network_zone': 'eu-central', 'type': 'cloud', 'server_name': 'molecule-hetznercloud-04f53935ed', 'network_name': 'molecule-hetznercloud-network-1'})
changed: [localhost] => (item={'ip': '10.20.10.1/24', 'server_name': 'molecule-hetznercloud-04f53935ed', 'network_name': 'molecule-hetznercloud-network-2'})

TASK [Attach Server to Subnetwork(s)] ******************************************
changed: [localhost] => (item={'ip': '10.10.10.1/24', 'network_zone': 'eu-central', 'type': 'cloud', 'server_name': 'molecule-hetznercloud-04f53935ed', 'network_name': 'molecule-hetznercloud-network-1'})
changed: [localhost] => (item={'ip': '10.20.10.1/24', 'server_name': 'molecule-hetznercloud-04f53935ed', 'network_name': 'molecule-hetznercloud-network-2'})
```  


> I'd like to take this opportunity to again emphasise that if Hetnzer GmbH are using this software internally (from this PR and https://github.com/hetznercloud/molecule-hetznercloud this would seem the case) then they should support the maintenance of it. Financial sponsorship is easier than ever, please see https://github.com/ansible-community/molecule-hetznercloud#support for how to do that. I've worked at tech companies where I also petitioned management to support open source so there is also something you can do as a worker. Thanks for considering 🌞

I forwarded this to Management :)

**Comment by decentral1se** [comment]
Thanks @ggggut! Yes, it must have been something from my local setup. I've merged this in https://github.com/ansible-community/molecule-hetznercloud/commit/6c4c20baa62df636a16aa4a090b4947b594052f1 and released it in https://pypi.org/project/molecule-hetznercloud/1.2.0/ :rocket:

**Comment by ggggut** [comment]
Thank you!

**Pull request closed without merging**
